import json
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from types import SimpleNamespace

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(ROOT / "bin"))

import ig_watch_ballard  # noqa: E402
import instaloader  # noqa: E402


# ---------------------------------------------------------------------------
# state / queue / log file helpers - pure I/O, no network
# ---------------------------------------------------------------------------

def test_load_state_missing_file_returns_default(tmp_path):
    state = ig_watch_ballard.load_state(tmp_path / "state.json")
    assert state == {"queued_shortcodes": []}


def test_load_state_corrupt_json_warns_and_returns_default(tmp_path, capsys):
    state_file = tmp_path / "state.json"
    state_file.write_text("not valid json {{{")
    state = ig_watch_ballard.load_state(state_file)
    assert state == {"queued_shortcodes": []}
    assert "unreadable/corrupt" in capsys.readouterr().err


def test_save_and_load_state_roundtrip(tmp_path):
    state_file = tmp_path / "sub" / "state.json"
    ig_watch_ballard.save_state(state_file, {"queued_shortcodes": ["abc123"]})
    reloaded = ig_watch_ballard.load_state(state_file)
    assert reloaded == {"queued_shortcodes": ["abc123"]}


def test_append_queue_entry_appends_jsonl_lines(tmp_path):
    queue_file = tmp_path / "queue.jsonl"
    ig_watch_ballard.append_queue_entry(queue_file, {"shortcode": "aaa"})
    ig_watch_ballard.append_queue_entry(queue_file, {"shortcode": "bbb"})
    lines = queue_file.read_text().splitlines()
    assert len(lines) == 2
    assert json.loads(lines[0])["shortcode"] == "aaa"
    assert json.loads(lines[1])["shortcode"] == "bbb"


def test_append_log_format(tmp_path):
    log_file = tmp_path / "log.txt"
    ig_watch_ballard.append_log(log_file, "checked tim_ballard89: 0 new")
    line = log_file.read_text().strip()
    ts, message = line.split(" ", 1)
    assert datetime.fromisoformat(ts)  # raises if not a real ISO timestamp
    assert message == "checked tim_ballard89: 0 new"


# ---------------------------------------------------------------------------
# find_todays_new_videos - feed-walking logic, fake Profile/Post, no network
# ---------------------------------------------------------------------------

@dataclass
class FakePost:
    shortcode: str
    is_video: bool
    date_local: datetime
    caption: str = ""


class FakeProfile:
    def __init__(self, posts):
        self._posts = posts

    def get_posts(self):
        return iter(self._posts)


def test_find_todays_new_videos_filters_and_stops_at_older_post(monkeypatch):
    today = datetime.now()
    yesterday = today - timedelta(days=1)

    posts = [
        FakePost("new_video", True, today),
        FakePost("today_image", False, today),          # skipped: not a video
        FakePost("already_queued", True, today),          # skipped: in state
        FakePost("old_video", True, yesterday),           # triggers stop
        FakePost("never_reached", True, today),           # must not be yielded
    ]
    monkeypatch.setattr(
        instaloader.Profile, "from_username",
        staticmethod(lambda context, username: FakeProfile(posts)),
    )
    state = {"queued_shortcodes": ["already_queued"]}

    result = list(ig_watch_ballard.find_todays_new_videos(SimpleNamespace(context=None), "whoever", state))

    assert [p.shortcode for p in result] == ["new_video"]


def test_find_todays_new_videos_respects_max_posts_checked(monkeypatch):
    today = datetime.now()
    posts = [FakePost(f"vid_{i}", True, today) for i in range(5)]
    monkeypatch.setattr(
        instaloader.Profile, "from_username",
        staticmethod(lambda context, username: FakeProfile(posts)),
    )
    state = {"queued_shortcodes": []}

    result = list(ig_watch_ballard.find_todays_new_videos(SimpleNamespace(context=None), "whoever", state, max_posts_checked=2))

    assert [p.shortcode for p in result] == ["vid_0", "vid_1"]


# ---------------------------------------------------------------------------
# get_loader - cookie fallback chain, no real network (test_login is faked)
# ---------------------------------------------------------------------------

NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n"


def _write_fake_cookie_file(path):
    path.write_text(
        NETSCAPE_HEADER
        + ".instagram.com\tTRUE\t/\tTRUE\t1810157586\tsessionid\tfakevalue\n"
    )


class _FakeContext:
    def __init__(self, login_result):
        self._login_result = login_result
        self.username = None
        self.cookies_loaded = False

    def update_cookies(self, cookie):
        self.cookies_loaded = True

    def test_login(self):
        return self._login_result


def _fake_instaloader_factory(results):
    """results: list of test_login() return values, consumed in call order."""
    results = list(results)

    class _FakeInstaloader:
        def __init__(self, *args, **kwargs):
            self.context = _FakeContext(results.pop(0))

    return _FakeInstaloader


def test_get_loader_falls_back_to_second_cookie_file(tmp_path, monkeypatch, capsys):
    cookie_a = tmp_path / "a.txt"
    cookie_b = tmp_path / "b.txt"
    _write_fake_cookie_file(cookie_a)
    _write_fake_cookie_file(cookie_b)

    monkeypatch.setattr(
        ig_watch_ballard.instaloader, "Instaloader",
        _fake_instaloader_factory([None, "merrillp.jensen"]),
    )

    loader = ig_watch_ballard.get_loader([str(cookie_a), str(cookie_b)])

    assert loader.context.username == "merrillp.jensen"
    out = capsys.readouterr().out
    assert "merrillp.jensen" in out
    assert str(cookie_b) in out


def test_get_loader_skips_missing_file_and_uses_next(tmp_path, monkeypatch):
    missing = tmp_path / "does_not_exist.txt"
    cookie_b = tmp_path / "b.txt"
    _write_fake_cookie_file(cookie_b)

    monkeypatch.setattr(
        ig_watch_ballard.instaloader, "Instaloader",
        _fake_instaloader_factory(["merrillp.jensen"]),
    )

    loader = ig_watch_ballard.get_loader([str(missing), str(cookie_b)])
    assert loader.context.username == "merrillp.jensen"


def test_get_loader_exits_when_no_cookie_authenticates(tmp_path, monkeypatch):
    cookie_a = tmp_path / "a.txt"
    _write_fake_cookie_file(cookie_a)

    monkeypatch.setattr(
        ig_watch_ballard.instaloader, "Instaloader",
        _fake_instaloader_factory([None]),
    )

    with pytest.raises(SystemExit):
        ig_watch_ballard.get_loader([str(cookie_a)])


# ---------------------------------------------------------------------------
# main() - error handling and idempotency, get_loader/find_todays_new_videos faked
# ---------------------------------------------------------------------------

def _run_main(monkeypatch, tmp_path, posts, existing_state=None):
    queue_file = tmp_path / "queue.jsonl"
    state_file = tmp_path / "state.json"
    log_file = tmp_path / "log.txt"
    if existing_state is not None:
        state_file.write_text(json.dumps(existing_state))

    monkeypatch.setattr(ig_watch_ballard, "get_loader", lambda cookie_files: SimpleNamespace(context=None))
    monkeypatch.setattr(
        instaloader.Profile, "from_username",
        staticmethod(lambda context, username: FakeProfile(posts)),
    )
    monkeypatch.setattr(
        sys, "argv",
        [
            "ig_watch_ballard.py",
            "--queue-file", str(queue_file),
            "--state-file", str(state_file),
            "--log-file", str(log_file),
        ],
    )
    ig_watch_ballard.main()
    return queue_file, state_file, log_file


def test_main_is_idempotent_on_second_run(monkeypatch, tmp_path):
    today = datetime.now()
    posts = [FakePost("vid_1", True, today)]

    queue_file, state_file, log_file = _run_main(monkeypatch, tmp_path, posts)
    first_lines = queue_file.read_text().splitlines()
    assert len(first_lines) == 1

    # second run: same posts, state now already has vid_1 queued
    _run_main(monkeypatch, tmp_path, posts, existing_state=json.loads(state_file.read_text()))
    second_lines = queue_file.read_text().splitlines()
    assert len(second_lines) == 1  # no duplicate append
    assert "checked" in log_file.read_text()


def test_main_reports_connection_error_without_crashing(monkeypatch, tmp_path):
    queue_file = tmp_path / "queue.jsonl"
    state_file = tmp_path / "state.json"
    log_file = tmp_path / "log.txt"

    monkeypatch.setattr(ig_watch_ballard, "get_loader", lambda cookie_files: SimpleNamespace(context=None))

    def raise_429(context, username):
        raise instaloader.exceptions.AbortDownloadException("429 Too Many Requests")

    monkeypatch.setattr(instaloader.Profile, "from_username", staticmethod(raise_429))
    monkeypatch.setattr(
        sys, "argv",
        [
            "ig_watch_ballard.py",
            "--queue-file", str(queue_file),
            "--state-file", str(state_file),
            "--log-file", str(log_file),
        ],
    )

    with pytest.raises(SystemExit):
        ig_watch_ballard.main()

    assert "ERROR" in log_file.read_text()
    assert not queue_file.exists()
